### ISSUE TITLE
Missing .env in git repo

### ISSUE THREAD

**Issue by ScorpioCoding** [emad-zaamout/laravel-docker-nginx-php-fpm-opcache#1]
You need to create a sample .env file and store it in the repo

**Comment by emad-zaamout** [comment]
Hello. Although its a valid point, I am against adding .env or .env.example as it the point of this repository is to allow to easily copy into a new project without replacing the project's .env file.

I would suggest you use this repository instead as I include a starter Laravel 10 project, with more enhancements.
https://github.com/emad-zaamout/laravel-docker-performance-template
