### ISSUE TITLE
configuration issue

### ISSUE THREAD

**Issue by Eazio-io** [emad-zaamout/laravel-docker-nginx-php-fpm-opcache#2]
![docker error](https://github.com/emad-zaamout/laravel-docker-nginx-php-fpm-opcache/assets/134498766/27af6ba4-9771-4f25-b67c-9f482812beca)
![docker error 2](https://github.com/emad-zaamout/laravel-docker-nginx-php-fpm-opcache/assets/134498766/de4acb26-77c1-48b7-bf9a-5c4b2b859e00)

I'm having this issue  after running the container please tell me what ,I had done wrong during deployment  , I'm new in this field please help me

**Comment by emad-zaamout** [comment]
Hello. You need to run `composer install` inside your container
